movie:
  rentals:
    - id: "F001"
      title: "You've Got Mail"
      code: "REGULAR"
    - id: "F002"
      title: "Matrix"
      code: "REGULAR"
    - id: "F003"
      title: "Cars"
      code: "CHILDRENS"
    - id: "F004"
      title: "Fast & Furious X"
      code: "NEW"
